#spring:
#  application:
#    name: inventory-service
#  datasource:
#    url: jdbc:postgresql://${DB_HOST_URL}/${DB_NAME}?useSSL=false
#    username:
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#
##  sql:
##    init:
##      mode: always
##      data-locations: classpath:data.sql
#
#server:
#  servlet:
##    Before using the API Gateway.
##    context-path: /api/v1
#    #    After using the API Gateway.
#    context-path: /products
#  port: 9010
#
## Eureka client configs.
#eureka:
#  client:
#    service-url:
##      registering the inventory service to the eureka server using the below address of eureka server.
#      defaultZone: http://localhost:9000/eureka

      # Now using the config server for configurations.
spring:
  application:
    name: inventory-service
  config:
    import: configserver:http://localhost:9040