spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
  data:
    redis:
      # for local redis database.
#      host: localhost
#      port: 6379
      # for cloud redis database.
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: 14832
