apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
     name: myapp
     env: dev
spec:
  containers:
    - name: my-nginx-container
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"   # 500m(m -> milli cpu) -> half cpu, as 1000 -> 1 cpu
      ports:
        - containerPort: 80