apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:     # template for pods to be created.
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: new-container
          image: nginx
          ports:
            - containerPort: 80

