spring:
  application:
  name: config-server

#   Config server configs.
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PmCoder26/ecommerce-config-server
          username: PmCoder26
          password: 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
          default-label: main

server:
  port: 9040

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
