apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server-container
          image: parimalmatte/ecommerce-config-server
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DISCOVERY_SERVICE
              value: "discovery-service-service"
          ports:
            - containerPort: 9040

---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
spec:
  clusterIP: None
  selector:
    app: config-server
  ports:
    - port: 9040
      targetPort: 9040