apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service
spec:
  selector:
    matchLabels:
      app: discovery-service
  template:
    metadata:
      labels:
        app: discovery-service
    spec:
      containers:
        - name: discovery-service-container
          image: parimalmatte/ecommerce-discovery-service
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service-service
spec:
  clusterIP: None
  selector:
    app: discovery-service
  ports:
    - port: 8761
      targetPort: 8761
