apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service-container
          image: parimalmatte/ecommerce-inventory-service
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 9010

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-service
spec:
  clusterIP: None
  selector:
    app: inventory-service
  ports:
    - port: 9010
      targetPort: 9010