apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service-container
          image: parimalmatte/ecommerce-order-service
          resources:
            limits:
              memory: "400Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "100m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 9020

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-service
spec:
  clusterIP: None
  selector:
    app: order-service
  ports:
    - port: 9020
      targetPort: 9020
